update public.missions
set active = false
where active = true;

with new_missions(theme_key, audience, prompt_ko, prompt_en, sort_order) as (
  values
    ('friend_reality', 'friend', '지금 주변에서 제일 킹받는 물건은?', 'What’s the most annoying thing near you right now?', 1),
    ('friend_reality', 'friend', '지금 제일 안 치운 티 나는 곳은?', 'What spot screams “I haven’t cleaned this yet”?', 2),
    ('friend_reality', 'friend', '주변에서 제일 쓸데없는데 존재감 큰 건?', 'What’s the most useless thing around you taking up way too much attention?', 3),
    ('friend_reality', 'friend', '주변에서 친구한테 놀림당할 만한 건?', 'What around you would your friend roast you for?', 4),
    ('friend_reality', 'friend', '지금 내 현실을 가장 잘 보여주는 장면은?', 'What scene captures your real life best right now?', 5),
    ('friend_reality', 'friend', '주변에서 제일 하찮은데 웃긴 건?', 'What’s the most random but funny thing around you?', 6),
    ('friend_reality', 'friend', '주변에 “나중에 해야지” 하고 미룬 흔적은?', 'What’s something around you that screams “I’ll do it later”?', 7),
    ('friend_reality', 'friend', '지금 네 앞에 있는 현실은?', 'What’s the reality sitting right in front of you?', 8),
    ('friend_reality', 'friend', '지금 제일 킹받는 건?', 'What’s annoying you the most right now?', 9),
    ('friend_reality', 'friend', '지금 제일 웃긴 상황은?', 'What’s the funniest thing happening right now?', 10),
    ('friend_survival_items', 'friend', '오늘 하루 종일 갖고다닐 필수템?', 'What’s your must-carry item for today?', 1),
    ('friend_survival_items', 'friend', '오늘의 생존템은?', 'What’s getting you through today?', 2),
    ('friend_survival_items', 'friend', '오늘의 도파민 충전템은?', 'What’s your little dopamine boost today?', 3),
    ('friend_survival_items', 'friend', '오늘 하루 버티게 해줄 아이템은?', 'What item is helping you survive the day?', 4),
    ('friend_survival_items', 'friend', '지금 나한테 제일 필요한 건?', 'What do you need the most right now?', 5),
    ('friend_survival_items', 'friend', '지금 이 순간의 생존템은?', 'What’s your survival item at this exact moment?', 6),
    ('friend_survival_items', 'friend', '지금 제일 필요한 건?', 'What do you need most right now?', 7),
    ('friend_survival_items', 'friend', '오늘 너를 망칠 것 같은 유혹은?', 'What temptation might derail your day?', 8),
    ('friend_survival_items', 'friend', '오늘 나를 방해하는 유혹템은?', 'What tempting thing is distracting you today?', 9),
    ('friend_status_mood', 'friend', '지금 내 상태를 제일 잘 보여주는 한 컷은?', 'What photo shows your current state best?', 1),
    ('friend_status_mood', 'friend', '오늘 아침 상태를 보여줄 한 컷은?', 'Show your morning mood in one photo.', 2),
    ('friend_status_mood', 'friend', '오늘의 귀찮음을 보여주는 한 컷은?', 'Show today’s laziness in one photo.', 3),
    ('friend_status_mood', 'friend', '오늘 정신상태를 대신 말해줄 물건은?', 'What object sums up your mental state today?', 4),
    ('friend_status_mood', 'friend', '오늘 내 상태 한 컷으로 치면?', 'If your mood were one photo, what would it be?', 5),
    ('friend_status_mood', 'friend', '지금 내 표정이 말해주는 건?', 'What is your face saying right now?', 6),
    ('friend_status_mood', 'friend', '지금 내 정신상태는?', 'What’s your mental state right now?', 7),
    ('friend_status_mood', 'friend', '오늘 내 에너지 몇 퍼센트?', 'What percent is your energy at today?', 8),
    ('friend_status_mood', 'friend', '지금 네 상태 한마디로는?', 'Sum up your current state in one photo.', 9),
    ('friend_status_mood', 'friend', '지금 네 텐션 몇 퍼센트?', 'What’s your energy level right now?', 10),
    ('friend_face_selfie', 'friend', '지금 내 얼굴 상태 솔직히 어때?', 'Be honest. How is your face doing right now?', 1),
    ('friend_face_selfie', 'friend', '지금 내 추구미랑 현실 차이는?', 'How far is your aesthetic from reality right now?', 2),
    ('friend_face_selfie', 'friend', '오늘 내 패션 포인트는?', 'What’s your outfit highlight today?', 3),
    ('friend_face_selfie', 'friend', '오늘 내 옷 상태 괜찮은 척 가능?', 'Can your outfit pass as intentional today?', 4),
    ('friend_face_selfie', 'friend', '지금 내 머리 상태는 무슨 일?', 'What is your hair doing right now?', 5),
    ('friend_face_selfie', 'friend', '오늘 나의 귀여움 레벨은?', 'What’s your cuteness level today?', 6),
    ('friend_face_selfie', 'friend', '지금 내 눈빛 상태는?', 'What’s the look in your eyes right now?', 7),
    ('friend_face_selfie', 'friend', '지금 나의 현실 고증 셀카는?', 'Take the most real-life selfie of yourself right now.', 8),
    ('friend_glowup_lazy', 'friend', '오늘 갓생인 척 가능한 사진?', 'What photo makes you look like you have your life together today?', 1),
    ('friend_glowup_lazy', 'friend', '오늘 나름 열심히 산 순간은?', 'What moment made you feel like you tried today?', 2),
    ('friend_glowup_lazy', 'friend', '오늘 내가 한 일 중 제일 갓생 같은 건?', 'What’s the most got-my-life-together thing you did today?', 3),
    ('friend_live_update', 'friend', '지금 가고 있는 곳은?', 'Where are you headed right now?', 1),
    ('friend_live_update', 'friend', '지금 하고 있는 건?', 'What are you doing right now?', 2),
    ('friend_live_update', 'friend', '지금 먹고 싶은 건?', 'What are you craving right now?', 3),
    ('friend_live_update', 'friend', '지금 제일 귀찮은 건?', 'What feels the most annoying to do right now?', 4),
    ('friend_live_update', 'friend', '지금 같이 있는 사람은?', 'Who are you with right now?', 5),
    ('friend_live_update', 'friend', '지금 혼자 뭐 하는 중?', 'What are you doing alone right now?', 6),
    ('friend_live_update', 'friend', '지금 네 손이 하고 있는 일은?', 'What are your hands doing right now?', 7),
    ('friend_live_update', 'friend', '지금 네 주변 분위기는?', 'What’s the vibe around you right now?', 8),
    ('couple_affection_heart', 'couple', '무성의한데 사랑은 있는 한 컷', 'A low-effort photo that still says “I love you.”', 1),
    ('couple_affection_heart', 'couple', '오늘 나한테 보내는 하트는?', 'What heart are you sending me today?', 2),
    ('couple_affection_heart', 'couple', '지금 나한테 보내는 손하트는?', 'Send me a finger heart right now.', 3),
    ('couple_affection_heart', 'couple', '오늘 나한테 보내는 애정 한 컷은?', 'Send me one little love-coded photo today.', 4),
    ('couple_affection_heart', 'couple', '지금 나한테 줄 수 있는 제일 작은 하트는?', 'What’s the tiniest heart you can send me right now?', 5),
    ('couple_affection_heart', 'couple', '지금 나한테 보내는 애정 인증은?', 'Show me your proof of love right now.', 6),
    ('couple_affection_heart', 'couple', '지금 나한테 손하트 가능해?', 'Can you send me a finger heart right now?', 7),
    ('couple_affection_heart', 'couple', '지금 표정으로 하트 보내면?', 'Send me a heart using just your face.', 8),
    ('couple_affection_heart', 'couple', '한 손하트로 생존신고 가능?', 'Can you check in with just a finger heart?', 9),
    ('couple_affection_heart', 'couple', '나한테 보내는 오늘의 하트 포즈는?', 'What’s today’s heart pose for me?', 10),
    ('couple_affection_heart', 'couple', '지금 손으로만 사랑 표현 가능?', 'Can you say “I love you” with just your hands?', 11),
    ('couple_selfie_face', 'couple', '오늘 나한테만 주는 표정은?', 'What face are you making just for me today?', 1),
    ('couple_selfie_face', 'couple', '오늘 나한테 보내는 애교 한 컷은?', 'Send me one cute photo today.', 2),
    ('couple_selfie_face', 'couple', '지금 나한테 보내는 귀여운 척은?', 'Show me your best fake-cute look right now.', 3),
    ('couple_selfie_face', 'couple', '오늘 나한테만 허락되는 셀카는?', 'What selfie is just for me today?', 4),
    ('couple_selfie_face', 'couple', '오늘 나한테 보내는 미소는?', 'Send me your smile today.', 5),
    ('couple_selfie_face', 'couple', '오늘 나한테 보내는 반쪽 얼굴은?', 'Send me a half-face photo today.', 6),
    ('couple_selfie_face', 'couple', '오늘 나한테만 보내는 못난 표정은?', 'Send me your ugliest cute face today.', 7),
    ('couple_selfie_face', 'couple', '지금 나한테 보내는 예쁜 척은?', 'Show me your “trying to look pretty” face right now.', 8),
    ('couple_selfie_face', 'couple', '오늘 나한테 보내는 대충 귀여운 한 컷은?', 'Send me a casually cute photo today.', 9),
    ('couple_selfie_face', 'couple', '오늘 나한테 보여주고 싶은 네 얼굴은?', 'What face do you want me to see today?', 10),
    ('couple_selfie_face', 'couple', '지금 나한테 보내는 머리 상태는?', 'Show me your hair situation right now.', 11),
    ('couple_selfie_face', 'couple', '지금 나한테 보내는 졸린 얼굴은?', 'Send me your sleepy face right now.', 12),
    ('couple_selfie_face', 'couple', '오늘 나한테 보내는 장난스러운 표정은?', 'Send me your playful face today.', 13),
    ('couple_selfie_face', 'couple', '지금 나한테만 보내는 눈빛은?', 'What look in your eyes is just for me right now?', 14),
    ('couple_selfie_face', 'couple', '오늘 나한테 보내는 귀여움은 몇 점?', 'What’s your cuteness score for me today?', 15),
    ('couple_selfie_face', 'couple', '오늘의 애인 전용 셀카는?', 'What’s today’s just-for-me selfie?', 16),
    ('couple_selfie_face', 'couple', '오늘의 귀여운 척 어디까지 가능해?', 'How far can you push the cute act today?', 17),
    ('couple_selfie_face', 'couple', '지금 얼굴 반만 나와도 되니까 한 컷 가능?', 'Can I get a photo, even if it’s just half your face?', 18),
    ('couple_selfie_face', 'couple', '오늘 애교 한 방 가능?', 'Can I get one cute move from you today?', 19),
    ('couple_selfie_face', 'couple', '지금 눈만 보여줘도 분위기 나오나?', 'Can you make it work with just your eyes?', 20),
    ('couple_selfie_face', 'couple', '오늘 나한테만 주는 미소는?', 'What smile is just for me today?', 21),
    ('couple_selfie_face', 'couple', '지금 카메라 보자마자 나오는 표정은?', 'What face do you make the second you see the camera?', 22),
    ('couple_selfie_face', 'couple', '오늘 나 설레게 할 한 컷 가능?', 'Can you send me one photo that makes my heart skip?', 23),
    ('couple_selfie_face', 'couple', '지금 제일 애인같은 사진 한 장 뽑자면?', 'What photo gives the most “I’m yours” energy right now?', 24),
    ('couple_miss_checkin', 'couple', '지금 나한테 보내는 생존신고는?', 'Send me a little “I’m alive” check-in.', 1),
    ('couple_miss_checkin', 'couple', '지금 나한테 보내는 보고싶음은?', 'Show me how much you miss me right now.', 2),
    ('couple_miss_checkin', 'couple', '지금 나한테 보내는 애인 모드는?', 'Show me your partner energy right now.', 3),
    ('couple_miss_checkin', 'couple', '지금 나한테 보내는 “나 여기 있어”는?', 'Send me your “I’m right here” photo.', 4),
    ('couple_miss_checkin', 'couple', '오늘 나한테 보내는 “보고 싶어” 대신 한 컷은?', 'Send me one photo instead of saying “I miss you.”', 5),
    ('couple_miss_checkin', 'couple', '지금 나한테 보내는 “안아줘” 느낌은?', 'Show me your “hug me” mood right now.', 6),
    ('couple_miss_checkin', 'couple', '오늘 나한테만 알려주는 근황은?', 'What little update is just for me today?', 7),
    ('couple_miss_checkin', 'couple', '오늘의 애인 전용 근황', 'Today’s partner-only update.', 8),
    ('couple_charm_crush', 'couple', '지금 나한테 자랑하고 싶은 포인트는?', 'What do you want to show off to me right now?', 1),
    ('couple_charm_crush', 'couple', '오늘의 심쿵 포인트는?', 'What’s your little heart-skip moment today?', 2),
    ('couple_charm_crush', 'couple', '손하트 말고 네가 제일 자신 있는 포즈는?', 'What pose are you most confident in, besides a finger heart?', 3),
    ('couple_together_moment', 'couple', '지금 나 대신 옆에 있는 건?', 'What’s next to you instead of me right now?', 1),
    ('couple_together_moment', 'couple', '오늘 나랑 같이 먹고 싶었던 건?', 'What did you wish we could eat together today?', 2),
    ('couple_together_moment', 'couple', '지금 나랑 같이 보고 싶은 건?', 'What do you wish we could look at together right now?', 3),
    ('couple_together_moment', 'couple', '지금 나한테 보내는 일상 한 조각은?', 'Send me a little piece of your day.', 4),
    ('couple_together_moment', 'couple', '지금 같이 찍는 척 옆자리 비워줄래?', 'Leave a spot for me like we’re taking the photo together.', 5),
    ('couple_together_moment', 'couple', '오늘의 커플짤 느낌 가능?', 'Can you make it feel like a couple photo today?', 6),
    ('couple_pose_mirror', 'couple', '지금 나한테 보내는 브이는?', 'Send me your peace sign right now.', 1),
    ('couple_pose_mirror', 'couple', '지금 거울샷 한 장 가능?', 'Can I get a mirror selfie right now?', 2),
    ('couple_pose_mirror', 'couple', '거울샷 한 장 어때?', 'How about one mirror selfie?', 3),
    ('couple_pose_mirror', 'couple', '지금 제일 자신 있는 포즈는?', 'What’s your most confident pose right now?', 4),
    ('couple_pose_mirror', 'couple', '오늘의 커플포즈!', 'Today’s couple pose!', 5),
    ('common_face_checkin', 'common', '지금 브이 할 기분이야?', 'Are you in the mood for a peace sign right now?', 1),
    ('common_face_checkin', 'common', '지금 얼굴 생존신고', 'Face check-in. Prove you’re alive.', 2),
    ('common_face_checkin', 'common', '오늘 졸림 레벨 몇 점?', 'What’s your sleepiness level today?', 3),
    ('common_face_checkin', 'common', '나한테만 보내는 대충 귀여운 척', 'A casually cute look just for me.', 4),
    ('common_face_checkin', 'common', '지금 표정으로 말해. “나 살아있다”', 'Say “I’m alive” with your face.', 5),
    ('common_face_checkin', 'common', '오늘 얼굴 상태 폼 좋음? 망함?', 'Is your face having a good day or not?', 6),
    ('common_face_checkin', 'common', '지금 나 보면 뭐라고 할 것 같아?', 'If I saw you right now, what would I say?', 7),
    ('common_face_checkin', 'common', '오늘의 귀찮음 max 표정', 'Show me your maximum “I can’t be bothered” face.', 8),
    ('common_face_checkin', 'common', '머리 상태 괜찮은 척 가능?', 'Can your hair pretend it’s fine today?', 9),
    ('common_face_checkin', 'common', '지금 너 표정 약간 수상한데?', 'Your face looks a little suspicious right now.', 10),
    ('common_current_scene', 'common', '지금 나 대신 네 옆에 있는 건?', 'What’s next to you instead of me right now?', 1),
    ('common_current_scene', 'common', '지금 네가 보고 있는 장면은?', 'What are you looking at right now?', 2),
    ('common_current_scene', 'common', '지금 어디에 앉아 있어?', 'Where are you sitting right now?', 3),
    ('common_current_scene', 'common', '오늘 너랑 제일 오래 붙어있을 건?', 'What’s been by your side the longest today?', 4),
    ('common_current_scene', 'common', '지금 나한테 제일 보여주고 싶은 별거 아닌 건?', 'What tiny random thing do you want to show me right now?', 5),
    ('common_current_scene', 'common', '지금 네 하루의 배경은?', 'What’s the background of your day right now?', 6),
    ('common_current_scene', 'common', '지금 나 몰래 먹고 있는 거 있어?', 'Are you secretly eating something right now?', 7),
    ('common_current_scene', 'common', '지금 네 주변에서 제일 너 같은 건?', 'What around you feels the most like you?', 8),
    ('common_background_place', 'common', '지금 네가 있는 곳의 분위기는?', 'What’s the vibe of where you are right now?', 1),
    ('common_background_place', 'common', '오늘 네 하루 배경은?', 'What’s the backdrop of your day?', 2),
    ('common_background_place', 'common', '지금 눈앞에 펼쳐진 장면은?', 'What’s the scene in front of you right now?', 3),
    ('common_background_place', 'common', '오늘 제일 오래 머문 곳은?', 'Where did you spend the most time today?', 4),
    ('common_background_place', 'common', '지금 네 시야 그대로는?', 'Show exactly what you’re seeing right now.', 5),
    ('common_background_place', 'common', '오늘 가장 많이 본 풍경은?', 'What view did you see the most today?', 6),
    ('common_background_place', 'common', '지금 너를 둘러싼 색감은?', 'What colors are surrounding you right now?', 7),
    ('common_background_place', 'common', '오늘의 이동 중 한 장면은?', 'Show one moment from being on the move today.', 8),
    ('common_background_place', 'common', '지금 제일 조용한 구석은?', 'What’s the quietest corner near you right now?', 9),
    ('common_background_place', 'common', '오늘 가장 정신없는 공간은?', 'What was the most chaotic place today?', 10),
    ('common_background_place', 'common', '지금 네 하루가 시작된 곳은?', 'Where did your day start?', 11),
    ('common_background_place', 'common', '오늘의 현실 고증 배경은?', 'What background captures your real day best?', 12),
    ('common_background_place', 'common', '지금 제일 마음에 드는 구석은?', 'What corner do you like most right now?', 13),
    ('common_background_place', 'common', '오늘 그냥 지나치기 아까운 장면은?', 'What scene felt too good to just pass by today?', 14),
    ('common_background_place', 'common', '지금 네 앞의 빛은?', 'What does the light in front of you look like?', 15),
    ('common_background_place', 'common', '오늘 제일 감성 있어 보이는 배경은?', 'What background looked the most aesthetic today?', 16),
    ('common_background_place', 'common', '지금 네 주변에서 제일 영화 같은 장면은?', 'What around you feels the most cinematic right now?', 17),
    ('common_background_place', 'common', '오늘 네가 서 있는 자리의 풍경은?', 'What’s the view from where you’re standing today?', 18),
    ('common_background_place', 'common', '지금 가장 생활감 있는 장면은?', 'What scene feels the most lived-in right now?', 19),
    ('common_background_place', 'common', '오늘의 배경화면 후보는?', 'What could be today’s wallpaper photo?', 20),
    ('common_background_place', 'common', '지금 네 하루의 무대는?', 'What’s the set of your day right now?', 21),
    ('common_background_place', 'common', '오늘 제일 많이 지나친 길은?', 'What path did you pass by the most today?', 22),
    ('common_background_place', 'common', '지금 창밖은 어떤데?', 'What’s outside your window right now?', 23),
    ('common_background_place', 'common', '오늘 하늘 상태는?', 'What’s the sky doing today?', 24),
    ('common_background_place', 'common', '지금 네 주변에서 제일 평화로운 장면은?', 'What’s the calmest scene around you right now?', 25),
    ('common_background_place', 'common', '오늘 제일 바빠 보였던 곳은?', 'What place looked the busiest today?', 26),
    ('common_background_place', 'common', '지금 여기만의 분위기는?', 'What’s the vibe that only this place has?', 27),
    ('common_background_place', 'common', '오늘 네 기분이랑 어울리는 배경은?', 'What background matches your mood today?', 28),
    ('common_background_place', 'common', '지금 딱 너 있는 곳 티 나는 장면은?', 'What scene gives away exactly where you are?', 29),
    ('common_background_place', 'common', '오늘 사진첩에 남길 만한 배경은?', 'What background deserves a spot in your camera roll today?', 30),
    ('common_fun_dopamine', 'common', '오늘 친구가 보면 캡처할 것 같은 사진은?', 'What photo would your friend screenshot today?', 1),
    ('common_fun_dopamine', 'common', '오늘 제일 눈길 가는 한 컷은?', 'What’s the most eye-catching shot today?', 2),
    ('common_fun_dopamine', 'common', '오늘 가장 큰 소비는?', 'What was your biggest purchase today?', 3),
    ('common_save_share', 'common', '오늘의 무조건 저장각 사진은?', 'What photo is an instant save today?', 1),
    ('common_save_share', 'common', '오늘의 스토리 올릴까 말까 고민되는 사진은?', 'What photo makes you wonder, “Should I post this?”', 2),
    ('common_save_share', 'common', '오늘의 아무도 안 믿을 근황샷은?', 'What update photo would nobody believe today?', 3),
    ('common_save_share', 'common', '오늘의 “이건 보내야겠다” 싶은 사진은?', 'What photo made you think, “I have to send this”?', 4),
    ('common_save_share', 'common', '오늘의 제일 어이없는 한 컷은?', 'What’s the most ridiculous shot today?', 5),
    ('common_save_share', 'common', '오늘의 제일 날것의 사진은?', 'What’s your most unfiltered photo today?', 6),
    ('common_save_share', 'common', '오늘의 제일 너다운 사진은?', 'What’s the most “you” photo today?', 7),
    ('common_save_share', 'common', '오늘의 단톡방 투척용 사진은?', 'What photo belongs in the group chat today?', 8),
    ('common_save_share', 'common', '오늘의 놀림감 예약 사진은?', 'What photo is basically asking to get roasted?', 9),
    ('common_save_share', 'common', '오늘의 웃긴데 좀 민망한 사진은?', 'What photo is funny but a little embarrassing?', 10),
    ('common_save_share', 'common', '오늘의 현실 고증 제대로 된 사진은?', 'What photo captures today’s reality a little too well?', 11),
    ('common_emotional_record', 'common', '오늘 나를 가장 행복하게 만든 것은?', 'What made you happiest today?', 1),
    ('common_emotional_record', 'common', '오늘 괜히 오래 보고 싶었던 것은?', 'What did you want to keep looking at today?', 2),
    ('common_emotional_record', 'common', '오늘 마음이 조금 편해진 순간은?', 'What moment made you feel a little lighter today?', 3),
    ('common_emotional_record', 'common', '오늘 가장 귀여웠던 것은?', 'What was the cutest thing today?', 4),
    ('common_emotional_record', 'common', '오늘 나를 웃게 만든 작은 것은?', 'What small thing made you smile today?', 5),
    ('common_emotional_record', 'common', '오늘의 가장 따뜻한 장면은?', 'What was the warmest scene today?', 6),
    ('common_emotional_record', 'common', '오늘 그냥 지나치기 아까운 것은?', 'What felt too nice to just pass by today?', 7),
    ('common_emotional_record', 'common', '오늘 나를 잠깐 멈추게 한 것은?', 'What made you pause for a moment today?', 8),
    ('common_emotional_record', 'common', '오늘 가장 오래 기억하고 싶은 장면은?', 'What scene do you want to remember the longest?', 9),
    ('common_emotional_record', 'common', '오늘 나에게 작은 위로가 된 것은?', 'What gave you a little comfort today?', 10),
    ('common_emotional_record', 'common', '오늘의 기분을 닮은 색은?', 'What color matches your mood today?', 11),
    ('common_emotional_record', 'common', '오늘 나를 살짝 설레게 한 것은?', 'What gave you a tiny spark today?', 12),
    ('common_emotional_record', 'common', '오늘 생각보다 마음에 들었던 순간은?', 'What moment did you like more than expected today?', 13),
    ('common_emotional_record', 'common', '오늘 나에게 다정했던 것은?', 'What felt kind to you today?', 14),
    ('common_emotional_record', 'common', '오늘의 작은 행운은?', 'What was your little lucky moment today?', 15),
    ('common_emotional_record', 'common', '오늘 나를 기분 좋게 만든 빛은?', 'What light made you feel good today?', 16),
    ('common_emotional_record', 'common', '오늘 그냥 예뻐 보였던 것은?', 'What simply looked pretty today?', 17),
    ('common_emotional_record', 'common', '오늘 나에게 필요한 평화는?', 'What peace did you need today?', 18),
    ('common_emotional_record', 'common', '오늘 나를 미소 짓게 한 것은?', 'What made you smile today?', 19),
    ('common_emotional_record', 'common', '오늘 내 하루에 남기고 싶은 한 조각은?', 'What piece of today do you want to keep?', 20),
    ('common_emotional_record', 'common', '오늘 나를 조금 더 괜찮게 만든 것은?', 'What made you feel a little more okay today?', 21),
    ('common_emotional_record', 'common', '오늘의 소소한 행복은?', 'What was your small happiness today?', 22),
    ('common_emotional_record', 'common', '오늘 나에게 선물 같았던 것은?', 'What felt like a little gift today?', 23),
    ('common_emotional_record', 'common', '오늘 가장 나답다고 느낀 순간은?', 'When did you feel most like yourself today?', 24),
    ('common_emotional_record', 'common', '오늘 괜히 사진으로 남기고 싶은 것은?', 'What did you randomly want to save as a photo today?', 25),
    ('common_emotional_record', 'common', '오늘 나에게 조용히 힘이 된 것은?', 'What quietly gave you strength today?', 26),
    ('common_emotional_record', 'common', '오늘 내 마음을 가볍게 만든 것은?', 'What made your heart feel lighter today?', 27),
    ('common_emotional_record', 'common', '오늘 나를 반짝이게 만든 것은?', 'What made you glow a little today?', 28),
    ('common_emotional_record', 'common', '오늘 나에게 오래 남을 것 같은 장면은?', 'What scene feels like it’ll stay with you?', 29),
    ('common_emotional_record', 'common', '오늘의 끝에 가져가고 싶은 것은?', 'What do you want to carry with you from today?', 30)
)
insert into public.missions (
  prompt_ko,
  prompt_en,
  mission_type,
  active,
  sort_order,
  audience,
  theme_key
)
select
  prompt_ko,
  prompt_en,
  'photo',
  true,
  sort_order,
  audience,
  theme_key
from new_missions;

do $$
declare
  v_active_count int;
  v_invalid_count int;
begin
  select count(*) into v_active_count
  from public.missions
  where active = true;

  if v_active_count <> 197 then
    raise exception 'expected 197 active missions, found %', v_active_count;
  end if;

  select count(*) into v_invalid_count
  from public.missions
  where active = true
    and (
      audience not in ('friend', 'couple', 'common')
      or theme_key is null
      or prompt_ko is null
      or prompt_en is null
    );

  if v_invalid_count <> 0 then
    raise exception 'active mission validation failed for % rows', v_invalid_count;
  end if;
end $$;
